CONTROL_DATA = [
    {
        "id": "GOV-01",
        "control": "Risk management governance",
        "domain": "Governance",
        "framework": "NIST CSF 2.0",
        "owner": "CISO",
        "status": "Implemented",
        "status_score": 90,
        "likelihood": 2,
        "impact": 2,
        "evidence": "Board risk register, quarterly review pack",
        "risk_level": "Low",
        "due_date": "2026-11-30",
        "note": "Board approves annual risk appetite and quarterly reporting.",
    },
    {
        "id": "GOV-02",
        "control": "Information security policy",
        "domain": "Governance",
        "framework": "ISO 27001 Annex A",
        "owner": "Security Manager",
        "status": "Partially implemented",
        "status_score": 72,
        "likelihood": 3,
        "impact": 3,
        "evidence": "Policy library with exception log",
        "risk_level": "Moderate",
        "due_date": "2026-10-20",
        "note": "Policy updates need stronger evidence retention tracking.",
    },
    {
        "id": "GOV-03",
        "control": "Top management accountability",
        "domain": "Governance",
        "framework": "NIS2",
        "owner": "CEO",
        "status": "Implemented",
        "status_score": 88,
        "likelihood": 2,
        "impact": 3,
        "evidence": "Management attestation and cyber steering committee minutes",
        "risk_level": "Low",
        "due_date": "2026-12-10",
        "note": "Leadership oversight is in place and reviewed quarterly.",
    },
    {
        "id": "IDENT-01",
        "control": "Asset inventory and ownership",
        "domain": "Identify",
        "framework": "NIST CSF 2.0",
        "owner": "IT Operations",
        "status": "Partially implemented",
        "status_score": 68,
        "likelihood": 3,
        "impact": 3,
        "evidence": "CMDB and ownership register",
        "risk_level": "Moderate",
        "due_date": "2026-11-02",
        "note": "Critical cloud assets still require evidence validation.",
    },
    {
        "id": "PROTECT-01",
        "control": "Access control and least privilege",
        "domain": "Protect",
        "framework": "ISO 27001 Annex A",
        "owner": "IAM Team",
        "status": "Implemented",
        "status_score": 86,
        "likelihood": 2,
        "impact": 4,
        "evidence": "Role-based controls and quarterly access review logs",
        "risk_level": "Low",
        "due_date": "2026-12-01",
        "note": "Access recertification cadence is operating but needs automation.",
    },
    {
        "id": "PROTECT-02",
        "control": "Secure configuration management",
        "domain": "Protect",
        "framework": "NIS2",
        "owner": "Platform Engineering",
        "status": "Partially implemented",
        "status_score": 64,
        "likelihood": 4,
        "impact": 4,
        "evidence": "Baseline hardening checklist and exceptions register",
        "risk_level": "High",
        "due_date": "2026-10-15",
        "note": "Legacy systems create residual risk and increase remediation urgency.",
    },
    {
        "id": "DETECT-01",
        "control": "Security monitoring and alerting",
        "domain": "Detect",
        "framework": "NIST CSF 2.0",
        "owner": "SOC",
        "status": "Implemented",
        "status_score": 83,
        "likelihood": 2,
        "impact": 4,
        "evidence": "SIEM dashboards and incident ticketing workflow",
        "risk_level": "Low",
        "due_date": "2026-12-11",
        "note": "Monitoring coverage is broad but still needs tuning for false positives.",
    },
    {
        "id": "RESPOND-01",
        "control": "Incident response process",
        "domain": "Respond",
        "framework": "NIS2",
        "owner": "Incident Manager",
        "status": "Implemented",
        "status_score": 80,
        "likelihood": 3,
        "impact": 4,
        "evidence": "IR playbooks and tabletop exercise records",
        "risk_level": "Moderate",
        "due_date": "2026-11-15",
        "note": "Exercises are completed, but vendor communications need clearer escalation paths.",
    },
    {
        "id": "RECOVER-01",
        "control": "Backup and recovery testing",
        "domain": "Recover",
        "framework": "ISO 27001 Annex A",
        "owner": "Infrastructure Team",
        "status": "Partially implemented",
        "status_score": 70,
        "likelihood": 3,
        "impact": 4,
        "evidence": "Backup logs and restore validation records",
        "risk_level": "Moderate",
        "due_date": "2026-11-05",
        "note": (
            "Restore validation is periodic but not yet fully automated across all "
            "critical systems."
        ),
    },
    {
        "id": "PRIV-01",
        "control": "Data protection and privacy impact assessment",
        "domain": "Privacy",
        "framework": "GDPR",
        "owner": "DPO",
        "status": "Implemented",
        "status_score": 82,
        "likelihood": 2,
        "impact": 3,
        "evidence": "PIA records and DPIA review log",
        "risk_level": "Low",
        "due_date": "2026-12-20",
        "note": "Privacy process is documented and reviewed for changes in processing.",
    },
]
